global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'miracle_ros2'
    static_configs:
      - targets: ['ros2_miracle:9100']
        labels:
          instance: 'miracle'
